# Parte 1

**2:17** Un proceso de cambio democrático puede invocarse desde distintas perspectivas:
	- El surgimiento de una cultura democrática ciudadana 
	- La apertura de los medios de comunicación
	- La movilización de organizaciones sociales independientes
	- Circunstancia del exterior 


**5:45** El proceso democrático mexicano nace de una revolución. La constitución de 1917 legitimizo a los sucesivos regímenes revolucionarios .

**6:00** Formula de la revolución  en el poder en México :
	- Educación
	- Salud
	- Infraestructura
	- Paz social
En cambio de la democracia.

Daban paz y desarrollo  pero sin democracia 

Esta estructura funciono por la continuidad de los régimen revolucionarios


**6:44** el apoyo al régimen siempre estuvo acompañado con la posibilidad de influir en las decisiones gubernamentales y
obtener beneficios materiales y simbólicos. Esto facilito la cooptación de asociaciones e individuos organizados, conducir los 
cambios con mayor facilidad y encausar la energía de las masas populares.

Esto era un autoritarismo incluyente, por el hecho de que todos podían entrar ahí mientras aceptaran las reglas centrales del juego
no había discriminación por creencias solo a los  no disciplinados 




## Origen revolucionario 

Las instituciones políticas incluyentes se originaron en la revolución de 1910.

**El porfiriato**
logro pacificar el país después de décadas de guerras civiles e invasiones, había logrado un apreciable crecimiento económico
pero la paz se mantenía a costa la libertad y la participación de la gente. La economía se sostenía gracias a los grandes
latifundios y terribles condiciones de trabajo. El resultado, fue una gran desigualdad y la monopolización de la vida política 
por una dictadura que duro 3 décadas. 

**8:10** resultado de la desigualdad 
La revolución fue una reacción a la desigualdad  y a la falta de oportunidades políticas  
- Una de las principales demandas fue la democracia. Como lo marca el lema maderista *Sufragio Efectivo. No-Reelección San Luis Potosí, Octubre 5 de 1910*


## 8:50 Gobierno de Francisco y Madero 

Fue inestable, incapaz de detener la milicia porfirista, ni pudo satisfacer las demandas de algunas facciones revolucionarias.


Con la traición de Huerta a Madero se reavivo el movimiento revolucionario, con demandas adicionales 

- Villistas y Zapatistas pedían el reparto de la tierra
- los constitucionalistas de Carranza y Obregón Demandaban derechos laborales


## 9:47 Constitución de 1917 
Sintetizo los reclamos de los distintos grupos revolucionarios.
- Campesino: Reforma Agraria  
- Obrero: Derecho laboral
- Ciudadanos: Garantías individuales
- Empresario: Libertad económica con tutela del estado

Para todos nacionalismo al limitar la presencia de extranjeros.

Carranza fue el primer presidente al utilizar esta constitución
- hizo alianzas con los empresarios, obreros, campesinos y la clase media 


14:06 **Caudillismo**

Alvaro Obregón ocupo la presidencia 1920-1924 emprendió una cruzada a favor la enseñanza y cultura.
- Adolfo de la Huerta encabezo una revolución Plutarco Elías Calles fue electo a la sustitución.


**15:16** 1928 el país aún se resentía por problemas políticos 

## La creación del PNR 


**16:40** Plutarco Elías Calles funda el partido Nacional Revolucionario 
- Se dio cuenta que el país necesitaba una transición de un país de Caudillismo a una nación de instituciones

**PNR nació en Marzo en 1929** 

- Se repartieron el poder entre los partidos creados por los caudillos.

Con la creación del PNR se inicio una etapa para la creación de instituciones capaces de contener y guiar la energía política generada por la revolución 
- pero sobre todo **aglutino a los caudillos de la lucha armada y caciques en una sola instituciones.** 

- En el PNR se pugnaba por el poder y se negociaban sus beneficios.

  Gracias al NPR el presidente Calles legitimizo su liderazgo sobre los candidatos. 

**La hegemonía del PNR se consolido en 1933 con la ampliación de la no reelección presidencial a diputados y senadores**

## Lázaro Cárdenas

**1934** Tomo la presidencia Lázaro Cárdenas 

Tuvo el apoyo de Plutarco Elías Calles y tenia una alianza con el movimiento de masas populares

**Expropiación petrolera fue realizada en 1938**

Plan de gobierno:

- fortalecer la rectoría económica del estado
- impulsar la reforma agraria
- alentar la unidad obrera

En este periodo los sindicatos y organizaciones fueron instrumentos para impulsar las reformas sociales 


### CTM Confederación de Trabajadores de México 
**24 de febrero de 1936**
Vicente Lombardo Toledano fue designado el presidente

Cárdenas reparte tierras y las asociaciones de campesinos beneficiados se unen a la PNR


Cárdenas reinició la reestructuración del PNR a PRM 

1938 PNR cambia a PRM Partido de la Revolución Mexicana
se organizo en 4 sectores:
- obrero
- campesino
- militar
- popular

## Avila Camacho Presidente 1940-1946
sucesor de Lázaro Cárdenas 

- PRM necesito una nueva reestructuración de PRM para adecuarlo a la 
 **ley electoral de Enero de 1946**

En 1946 el PRI fue creado y fue integrado por 3 sectores:

- obrero

- campesino

- popular 


## Miguel Alemán Valdez
fue el primer candidato del PRI

## 1958

Se conoce como el **desarrollo estabilizador** . Esta política representa de sustitución de importaciones. Se ponen trabas a las 
importaciones mediante:

- aranceles elevados
- permisos de importación 

Ésto facilitó la producción interna de los productos, qué anteriormente se importaban



## 1946 

### Elecciones y legitimidad 44 

A través de las elecciones se reciclaban grupos y liderazgos para evitar que se perpetuaran en el poder

Nuestro sistema era una *Monarquía absoluta sexenal*

** Se creó una legislación electoral que se mantendría vigente a lo largo de 30 años .

**Se creó una ley para Federal Electoral que inicia el proceso de centralización de la organización de las elecciones mexicanas.
    
    - **además, de centralizar las elecciones establecía que en los comicios podían participar exclusivamente los partidos políticos reconocidos.**

## 1963

Se diseñó un sistema en donde se colocaba el partido oficial y partidos de oposición en 2 diferentes arenas electorales.

Se crean los diputados de partido:

- Por cada 2.5% que tuviera cada partido político se le daban 5 diputados. Por cada 0.5% se le daba un diputado adicional hasta llegar a 20.

**Esto independientemente de los diputados que ganarán o perdiera en los distintos de mayoría relativa**

** esta reforma evitó la violencia en México por que permito a la oposición de tener representación** 

El PAN paso de tener 3 diputados a tener 20. 

## PAN 

Nació  en 1939 y fue la principal oposición del régimen autoritario.

Fundado por Manuel Gómez Morín en 1939 

## PPS
Partido Popular Socialista fue fundado por Lombardo Toledano en 1938  durante el periodo de Miguel Alemán.

## Partido comunista mexicano 

1919 movimiento sindical 

## Elecciones mas discutidas

1929, 1940, 1952 por protestas por fraude José Vasconcelos, Andrew Almazán, Enrigue Guzmán 

Elecciones locales

SLP 1941
Sonora 1967
Yucatán 1969 

# Parte 2  Mexico convulsivo 1968 1976 


Milagro mexicano 

- 1958-1970 la economía crecio en promedio 6.8 % inflacion 2.5% 

El regimen otorgaba repartos a las zonas menos protegidas, fue el pilar del regimen 

- El desarollo que estaba alcanzando Mexico no llegaba a todos los rincones. EL milagro mexicano tenia limites estructurales y exhibia claras contradicciones 

- El impulso y las condiciones favorables no llegaron al campo. Donde el avance se limito al reparto de tierras. personas del campo.se vieron en la necesitad de mudarse a la cuidad para buscar mejores oportunidades.
  El campo era uno de los principales soportes del sistema politico mexicano.

- **No hay nada que pueda representar El autoritarismo del sistema politico mexicano como la represion del movimiento estudiantil
  de 1968** 
23 Junio 1968 Plaza de la cuidadela 
